<div class="row">
	<div class="col-lg-7">

		<!--Network Line Chart-->
		<!--===================================================-->
		<div id="demo-panel-network" class="panel">
			<div class="panel-heading">
				<h3 class="panel-title">Estad&iacute;sticas mensuales</h3>
			</div>

			<!--Morris line chart placeholder-->
			<div id="morris-chart-network" class="morris-full-content"></div>

			<!--Chart information-->
			<div class="panel-body bg-primary"
				style="position: relative; z-index: 2">
				<div class="row">
					<div class="col-lg-6">
						<div class="row">
							<div class="col-xs-8">

								<!--Server load stat-->
								<div class="pad-ver media">
									<div class="media-left">
										<span class="icon-wrap icon-wrap-xs"> <i
											class="fa fa-cloud fa-2x"></i>
										</span>
									</div>

									<div class="media-body">
										<p class="h3 text-thin media-heading">30%</p>
										<small class="text-uppercase">Ahorro total</small>
									</div>
								</div>

								<!--Progress bar-->
								<div class="progress progress-xs progress-dark-base mar-no">
									<div class="progress-bar progress-bar-light" style="width: 30%"></div>
								</div>

							</div>
							<div class="col-xs-4">
								<!-- User Online -->
								<div class="text-center">
									<span class="text-3x text-thin">43</span>
									<p>Usuarios en l&iacute;nea</p>
								</div>
							</div>
						</div>

					</div>
					<div class="col-lg-6">

						<!-- List Group -->
						<ul class="list-group bg-trans mar-no">
							<li class="list-group-item">
								<!-- Sparkline chart -->
								<div id="demo-chart-visitors" class="pull-right"></div> B&uacute;squedas
							</li>
							<li class="list-group-item">
								<!-- Sparkline chart -->
								<div id="demo-chart-bounce-rate" class="pull-right"></div>
								B&uacute;squedas Mensuales
							</li>
							<li class="list-group-item"><span class="badge badge-success">11</span>
								Hoy</li>
						</ul>

					</div>
				</div>
			</div>


		</div>
		<!--===================================================-->
		<!--End network line chart-->

	</div>
	<div class="col-lg-5">
		<div class="row">
			<!--Morris donut chart-->
			<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
			<div class="panel">
				<div class="panel-heading">
					<h3 class="panel-title">B&uacute;squedas por categor&iacute;a</h3>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-sm-12">
							<div class="pad-ver">
								<p class="text-lg">Avance de b&uacute;squedas mensuales</p>
								<div class="progress progress-sm">
									<div role="progressbar" style="width: 15%;" aria-valuemax="100"
										aria-valuemin="0" aria-valuenow="15"
										class="progress-bar progress-bar-purple">
										<span class="sr-only">15%</span>
									</div>
								</div>
								<small class="text-muted">15%</small>
							</div>
							<div class="pad-ver">
								<p class="text-lg">Usuarios Cr&iacute;ticos</p>
								<div class="progress progress-sm">
									<div role="progressbar" style="width: 70%;" aria-valuemax="100"
										aria-valuemin="0" aria-valuenow="70"
										class="progress-bar progress-bar-success">
										<span class="sr-only">70%</span>
									</div>
								</div>
								<small class="text-muted">70 de 1050 clientes</small>
							</div>

							<hr>
							<small class="text-muted"><em>Ultima actualizaci&oacute;n : Febrero 20, 2015</em></small>
						</div>
					</div>
				</div>
			</div>
			<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
			<!--End Morris donut chart-->
		</div>
	</div>
</div>



<div class="row">
	<div class="col-lg-12">

		<!--User table-->
		<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
		<div class="panel">
			<div class="panel-heading">
				<h3 class="panel-title">&Uacute;ltimos clientes buscados</h3>
			</div>

			<div class="panel-body">
				<div class="table-responsive">
					<table class="table table-striped table-hover">
						<thead>
							<tr>
								<th style="width: 4ex">ID</th>
								<th>Nombre</th>
								<th>Gasto aseguradora</th>
								<th class="text-center">&iquest;Cr&iacute;tico?</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><a href="#" class="btn-link">NY531</a></td>
								<td>Steve N. Horton</td>
								<td>$2400.98</td>
								<td class="text-center"><span
									class="label label-table label-danger">Alto</span></td>
							</tr>
							<tr>
								<td><a href="#" class="btn-link">NY532</a></td>
								<td>Scott S. Calabrese</td>
								<td>$543.65</td>
								<td class="text-center"><span
									class="label label-table label-warning">Medio</span></td>
							</tr>
							<tr>
								<td><a href="#" class="btn-link">NY533</a></td>
								<td>Teresa L. Doe</td>
								<td>$753.95</td>
								<td class="text-center"><span
									class="label label-table label-success">Bajo</span></td>
							</tr>
							<tr>
								<td><a href="#" class="btn-link">NY534</a></td>
								<td>Lucy Doe</td>
								<td>$2234.86</td>
								<td class="text-center"><span
									class="label label-table label-warning">Medio</span></td>
							</tr>
							<tr>
								<td><a href="#" class="btn-link">NY535</a></td>
								<td>Charles S Boyle</td>
								<td>$7675.32</td>
								<td class="text-center"><span
									class="label label-table label-danger">Alto</span></td>
							</tr>
							<tr>
								<td><a href="#" class="btn-link">NY536</a></td>
								<td>Paul Aguilar</td>
								<td>$1993.64</td>
								<td class="text-center"><span
									class="label label-table label-warning">Medio</span></td>
							</tr>
							<tr>
								<td><a href="#" class="btn-link">NY537</a></td>
								<td>Betty Murphy</td>
								<td>$5941.84</td>
								<td class="text-center"><span
									class="label label-table label-success">Bajo</span></td>
							</tr>
							<tr>
								<td><a href="#" class="btn-link">NY538</a></td>
								<td>Steve N. Horton</td>
								<td>$5834.77</td>
								<td class="text-center"><span
									class="label label-table label-danger">Alto</span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
		<!--End user table-->
	</div>
</div>