<!-- Le styles -->
<?php /* echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
           ->prependStylesheet($this->basePath() . '/template/assets/css/theme/default.css')
           ->prependStylesheet($this->basePath() . '/template/assets/css/style-responsive.min.css')
           ->prependStylesheet($this->basePath() . '/template/assets/css/style.min.css')
           ->prependStylesheet($this->basePath() . '/template/assets/css/animate.min.css')
           ->prependStylesheet($this->basePath() . '/template/assets/plugins/font-awesome/css/font-awesome.min.css')
           ->prependStylesheet($this->basePath() . '/template/assets/plugins/bootstrap/css/bootstrap.min.css')
           ->prependStylesheet($this->basePath() . '/template/assets/plugins/jquery-ui/themes/base/minified/jquery-ui.min.css', 'screen', true, array('id' => 'theme'))
           ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700') */ ?>
<!--STYLESHEET-->
	<!--=================================================-->

	<!--Open Sans Font [ OPTIONAL ] -->
 	<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;subset=latin" rel="stylesheet">


	<!--Bootstrap Stylesheet [ REQUIRED ]-->
	<link href="<?php echo $this->basepath() . '/template/css/bootstrap.min.css'?>" rel="stylesheet">


	<!--Nifty Stylesheet [ REQUIRED ]-->
	<link href="<?php echo $this->basepath() . '/template/css/nifty.min.css'?>" rel="stylesheet">

	
	<!--Font Awesome [ OPTIONAL ]-->
	<link href="<?php echo $this->basepath() . '/template/plugins/font-awesome/css/font-awesome.min.css'?>" rel="stylesheet">


	<!--Demo [ DEMONSTRATION ]-->
	<link href="<?php echo $this->basepath() . '/template/css/demo/nifty-demo.min.css'?>" rel="stylesheet">




	<!--SCRIPT-->
	<!--=================================================-->

	<!--Page Load Progress Bar [ OPTIONAL ]-->
	<link href="<?php echo $this->basepath() . '/template/plugins/pace/pace.min.css'?>" rel="stylesheet">
	<script src="<?php echo $this->basepath() . '/template/plugins/pace/pace.min.js'?>"></script>


	
	<!--

	REQUIRED
	You must include this in your project.

	RECOMMENDED
	This category must be included but you may modify which plugins or components which should be included in your project.

	OPTIONAL
	Optional plugins. You may choose whether to include it in your project or not.

	DEMONSTRATION
	This is to be removed, used for demonstration purposes only. This category must not be included in your project.

	SAMPLE
	Some script samples which explain how to initialize plugins or components. This category should not be included in your project.


	Detailed information and more samples can be found in the document.

	-->