<!--JAVASCRIPT-->
	<!--=================================================-->

	<!--jQuery [ REQUIRED ]-->
	<script src="<?php echo $this->basepath() . '/template/js/jquery-2.1.1.min.js'?>"></script>


	<!--BootstrapJS [ RECOMMENDED ]-->
	<script src="<?php echo $this->basepath() . '/template/js/bootstrap.min.js'?>"></script>


	<!--Fast Click [ OPTIONAL ]-->
	<script src="<?php echo $this->basepath() . '/template/plugins/fast-click/fastclick.min.js'?>"></script>

	
	<!--Nifty Admin [ RECOMMENDED ]-->
	<script src="<?php echo $this->basepath() . '/template/js/nifty.min.js'?>"></script>


	<!--Background Image [ DEMONSTRATION ]-->
	<script src="<?php echo $this->basepath() . '/template/js/demo/bg-images.js'?>"></script>
	
	<!--Switchery [ OPTIONAL ]-->
	<script src="<?php echo $this->basepath() . '/template/plugins/switchery/switchery.min.js'?>"></script>


	<!--Bootstrap Select [ OPTIONAL ]-->
	<script src="<?php echo $this->basepath() . '/template/plugins/bootstrap-select/bootstrap-select.min.js'?>"></script>


	<!--

	REQUIRED
	You must include this in your project.

	RECOMMENDED
	This category must be included but you may modify which plugins or components which should be included in your project.

	OPTIONAL
	Optional plugins. You may choose whether to include it in your project or not.

	DEMONSTRATION
	This is to be removed, used for demonstration purposes only. This category must not be included in your project.

	SAMPLE
	Some script samples which explain how to initialize plugins or components. This category should not be included in your project.

	Detailed information and more samples can be found in the document.

	-->