<!--MAIN NAVIGATION-->
			<!--===================================================-->
			<nav id="mainnav-container">
				<div id="mainnav">

					<!--Menu-->
					<!--================================-->
					<div id="mainnav-menu-wrap">
						<div class="nano">
							<div class="nano-content">
								<ul id="mainnav-menu" class="list-group">
						
									<!--Category name-->
									<li class="list-header"><strong>Opciones del Men&uacute;</strong></li>
						
									<!--Menu list item-->
									<li class="active-link">
										<a href="<?php echo $this->url('portal')?>">
											<i class="fa fa-dashboard"></i>
											<span class="menu-title">
												<strong>Dashboard</strong>
												<span class="label label-success pull-right">Inicio</span>
											</span>
										</a>
									</li>
									
									<li class="list-divider"></li>
						
									<!--Category name-->
									<li class="list-header"><strong>Informaci&oacute;n</strong></li>
									
									<!--Menu list item-->
									<li>
										<a href="<?php echo $this->url('portal', array('controller' => 'aseguradora', 'action' => 'perfil'))?>">
											<i class="fa fa-line-chart"></i>
											<span class="menu-title">Aseguradora</span>
										</a>
									</li>
									
									<li class="list-divider"></li>
						
									<!--Category name-->
									<li class="list-header"><strong>Asegurados</strong></li>
									
									<!--Menu list item-->
									<li>
										<a href="charts.html">
											<i class="fa fa-line-chart"></i>
											<span class="menu-title">B&uacute;squeda Individual</span>
										</a>
									</li>
									
									<!--Menu list item-->
									<li>
										<a href="charts.html">
											<i class="fa fa-line-chart"></i>
											<span class="menu-title">B&uacute;squeda Avanzada</span>
										</a>
									</li>
									
									<!--Menu list item-->
									<li>
										<a href="charts.html">
											<i class="fa fa-line-chart"></i>
											<span class="menu-title">Asegurados</span>
										</a>
									</li>
									
									<li class="list-divider"></li>
						
									<!--Category name-->
									<li class="list-header"><strong>Productos</strong></li>
									
									<!--Menu list item-->
									<li>
										<a href="charts.html">
											<i class="fa fa-line-chart"></i>
											<span class="menu-title">Listado de Productos</span>
										</a>
									</li>
						
									<li class="list-divider"></li>
						
									<!--Category name-->
									<li class="list-header"><strong>Reportes</strong></li>
						
									<!--Menu list item-->
									<li>
										<a href="charts.html">
											<i class="fa fa-line-chart"></i>
											<span class="menu-title">Reporte 1</span>
										</a>
									</li>
									
									<!--Menu list item-->
									<li>
										<a href="charts.html">
											<i class="fa fa-line-chart"></i>
											<span class="menu-title">Reporte 2</span>
										</a>
									</li>
									
									<!--Menu list item-->
									<li>
										<a href="charts.html">
											<i class="fa fa-line-chart"></i>
											<span class="menu-title">Reporte 3</span>
										</a>
									</li>
						
									<li class="list-divider"></li>
								</ul>
							</div>
						</div>
					</div>
					<!--================================-->
					<!--End menu-->

				</div>
			</nav>
			<!--===================================================-->
			<!--END MAIN NAVIGATION-->