<?php if(!$this->loggedIn): ?>
<div id="container" class="cls-container">
		
		<!-- BACKGROUND IMAGE -->
		<!--===================================================-->
		<div id="bg-overlay" class="bg-img img-balloon"></div>
		
		
		<!-- HEADER -->
		<!--===================================================-->
		<div class="cls-header cls-header-lg">
			<div class="cls-brand">
				<a class="box-inline" href="index.html">
					<!-- <img alt="Nifty Admin" src="img/logo.png" class="brand-icon"> -->
					<span class="brand-title">Administraci&oacute;n de <span class="text-thin">Seguros</span></span>
				</a>
			</div>
		</div>
		<!--===================================================-->
		
		
		<!-- LOGIN FORM -->
		<!--===================================================-->
		<div class="cls-content">
			<div class="cls-content-sm panel">
				<div class="panel-body">
					<p class="pad-btm">Ingresar en su cuenta...</p>
					<?php 
                    $form = $this->form;
                    $form->prepare ()->setAttribute ( 'action', $this->url ( 'application', array (
                    		'controller' => 'login',
                    		'action' => 'autenticar'
                    ) ) )->setAttribute ( 'method', 'post' )
                    ->setAttribute ( 'class', 'margin-bottom-0' );
                    $formLabel = $this->plugin ( 'formLabel' );
                    
                    echo $this->form()->openTag($form);
                    ?>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon"><i class="fa fa-user"></i></div>
								 <?php //campo usuario
                        		$email = $form->get('usu_usuario');
                        		echo $formLabel->openTag().$email->getOption('label');
                        		echo $formLabel->closeTag();
                        	   ?>
                        	   <?php //campo usuario
                    			echo $this->forminput($email);
                    			echo $this->formelementerrors($email);
                    			?>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon"><i class="fa fa-asterisk"></i></div>
								<?php 
                              $password = $form->get('usu_clave');
                              echo $formLabel->openTag().$password->getOption('label');
                              echo $formLabel->closeTag();
                              ?>
                              <?php //campo password
                    			echo $this->forminput($password);
                    			echo $this->formelementerrors($password);
                    			?>
							</div>
						</div>
						<?php $mensaje = $this->layout()->mensaje; if(!is_null($mensaje) && isset($mensaje)): ?>
                         <div class="alert alert-danger">
                            <strong>Error!</strong><br /><?php echo $this->layout()->mensaje; ?>
                            <span class="close" data-dismiss="alert">&times;</span>
                        </div>
                        <?php endif; ?>
						<div class="row">
							<div class="col-xs-12 text-left checkbox">
								<label class="form-checkbox form-icon">
								<input type="checkbox"> Recordarme
								</label>
							</div>
						</div>
						<div class="mar-btm"><em>&nbsp;</em></div>
						<?php echo $this->formelement($form->get('ingresar')) ?>
						<div class="pad-ver">
            				<a href="pages-password-reminder.html" class="btn-link mar-rgt" style="color: #000000 !important;">&iquest; Olvid&oacute; su contrase&ntilde;a?</a>
            			</div>
					<?php echo $this->form()->closeTag() ?>
				</div>
			</div>
			
		</div>
		<!--===================================================-->
	</div>
	<!--===================================================-->
	<!-- END OF CONTAINER -->
<?php endif; ?>