<div class="row">
	<div class="col-md-4 col-lg-4">
		<!--Profile Widget-->
		<!--===================================================-->
		<div class="panel text-center">
			<div class="panel-body">
				<img alt="Avatar" class="mar-btm"
					src="<?php echo $this->basepath() . '/img/jpg/' . $this->aseguradora->getAse_logo() ?>">
				<h4 class="mar-no"><?php echo $this->aseguradora->getAse_nombre()?></h4>
			</div>
			<div class="pad-ver">
				<a
					class="btn btn-default btn-icon btn-hover-primary fa fa-facebook icon-lg add-tooltip"
					href="<?php ?>" title="Facebook"></a> <a
					class="btn btn-default btn-icon btn-hover-info fa fa-twitter icon-lg add-tooltip"
					href="#" title="Twitter"></a> <a
					class="btn btn-default btn-icon btn-hover-danger fa fa-google-plus icon-lg add-tooltip"
					href="#" title="Google+"></a> <a
					class="btn btn-default btn-icon btn-hover-mint fa fa-envelope icon-lg add-tooltip"
					href="#" title="Email"></a>
			</div>
			<div class="panel-body text-justify">
				<h4>Descripci&oacute;n de la empresa</h4>
				<?php echo $this->aseguradora->getAse_descripcion()?>
				<br />
				<br />
				<div style="line-height: 25px;">
					<div>
						<strong>Email:</strong> <a href="#" class="btn-link"><?php echo $this->aseguradora->getAse_email()?></a>
					</div>
					<div>
						<strong>Direcci&oacute;n:</strong> <?php echo $this->aseguradora->getAse_direccion() ?></div>
					<div>
						<strong>Tel&eacute;fono:</strong> <?php echo $this->aseguradora->getAse_telefono() ?></div>
				</div>
			</div>
		</div>
		<!--===================================================-->
	</div>
	<div class="col-md-8 col-lg-8">
		<div class="panel text-center">
			<div class="panel-body text-justify">
	           <?php foreach ($this->clientes as $cliente):?>
	           <div class="col-md-3 col-lg-3">
					<!--Profile Widget-->
					<!--===================================================-->
					<div class="panel widget" style="border: 1px solid #F3F3F3;">
						<div class="widget-header bg-primary" style="min-height: 0px; padding-top: 0px;"></div>
						<div class="widget-body text-center" style="padding-bottom: 0px;">
						<?php $sexo = $cliente->getCli_sexo(); if($sexo == 'M'):?>
							<img alt="Profile Picture" class="widget-img img-circle img-border-light" src="<?php echo $this->basepath() . '/template/img/av2.png'?>">
							<?php else:?>
							<img alt="Profile Picture" class="widget-img img-circle img-border-light" src="<?php echo $this->basepath() . '/template/img/av6.png'?>">
						<?php endif;?>
							<h4 class="mar-no"><?php echo $cliente->getCli_nombre() . ' ' . $cliente->getCli_apellido()?></h4>
							<div class="pad-ver">
								<a href="<?php echo $this->url('portal', array('controller' => 'cliente', 'action' => 'perfil', 'id' => $cliente->getCli_id()))?>" class="btn btn-success">Perfil</a>
							</div>
						</div>
					</div>
					<!--===================================================-->
				</div>
	           <?php endforeach;?>
	       </div>
		</div>
	</div>
</div>