<?php echo $this->doctype(); ?>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<?php echo $this->headTitle('Sistema integral para el control de gastos') ?>
	
	<?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
        
	<?php echo $this->partial('partial/css')?>
</head>
<body>
    <?php echo $this->content; ?>
	<?php echo $this->partial('partial/js')?>
</body>
</html>